import { Bank, Category } from './types'

export const BANKS: Bank[] = [
  {
    id: 'famous-people',
    name: 'Famous People',
    items: [
      { id: 'fp-1', name: 'Albert Einstein' },
      { id: 'fp-2', name: 'Abraham Lincoln' },
      { id: 'fp-3', name: 'Cleopatra' },
      { id: 'fp-4', name: 'Napoleon Bonaparte' },
      { id: 'fp-5', name: 'Leonardo da Vinci' },
      { id: 'fp-6', name: 'Queen Elizabeth I' },
      { id: 'fp-7', name: 'Julius Caesar' },
      { id: 'fp-8', name: 'Genghis Khan' },
      { id: 'fp-9', name: 'Marie Curie' },
      { id: 'fp-10', name: 'Isaac Newton' },
      { id: 'fp-11', name: 'William Shakespeare' },
      { id: 'fp-12', name: 'Christopher Columbus' },
      { id: 'fp-13', name: 'Galileo Galilei' },
      { id: 'fp-14', name: 'Benjamin Franklin' },
      { id: 'fp-15', name: 'Joan of Arc' },
      { id: 'fp-16', name: 'Nikola Tesla' },
      { id: 'fp-17', name: 'Socrates' },
      { id: 'fp-18', name: 'Alexander the Great' },
      { id: 'fp-19', name: 'Martin Luther King Jr.' },
      { id: 'fp-20', name: 'Mahatma Gandhi' },
      { id: 'fp-21', name: 'Winston Churchill' },
      { id: 'fp-22', name: 'Adolf Hitler' },
      { id: 'fp-23', name: 'Joseph Stalin' },
      { id: 'fp-24', name: 'Mao Zedong' },
      { id: 'fp-25', name: 'Karl Marx' },
      { id: 'fp-26', name: 'Charles Darwin' },
      { id: 'fp-27', name: 'Sigmund Freud' },
      { id: 'fp-28', name: 'Walt Disney' },
      { id: 'fp-29', name: 'Elvis Presley' },
      { id: 'fp-30', name: 'Michael Jackson' },
      { id: 'fp-31', name: 'Muhammad Ali' },
      { id: 'fp-32', name: 'Nelson Mandela' },
      { id: 'fp-33', name: 'Mother Teresa' },
      { id: 'fp-34', name: 'Elon Musk' },
      { id: 'fp-35', name: 'Steve Jobs' },
      { id: 'fp-36', name: 'Bill Gates' },
      { id: 'fp-37', name: 'Oprah Winfrey' },
      { id: 'fp-38', name: 'Marilyn Monroe' },
      { id: 'fp-39', name: 'Audrey Hepburn' },
      { id: 'fp-40', name: 'Bruce Lee' },
      { id: 'fp-41', name: 'Freddie Mercury' },
      { id: 'fp-42', name: 'David Bowie' },
      { id: 'fp-43', name: 'John Lennon' },
      { id: 'fp-44', name: 'Bob Dylan' },
      { id: 'fp-45', name: 'Bob Marley' },
      { id: 'fp-46', name: 'Princess Diana' },
      { id: 'fp-47', name: 'Queen Victoria' },
      { id: 'fp-48', name: 'George Washington' },
      { id: 'fp-49', name: 'Thomas Jefferson' },
      { id: 'fp-50', name: 'Theodore Roosevelt' },
      { id: 'fp-51', name: 'Franklin D. Roosevelt' },
      { id: 'fp-52', name: 'John F. Kennedy' },
      { id: 'fp-53', name: 'Ronald Reagan' },
      { id: 'fp-54', name: 'Barack Obama' },
      { id: 'fp-55', name: 'Donald Trump' },
      { id: 'fp-56', name: 'Aristotle' },
      { id: 'fp-57', name: 'Plato' },
      { id: 'fp-58', name: 'Confucius' },
      { id: 'fp-59', name: 'Sun Tzu' },
      { id: 'fp-60', name: 'Marco Polo' },
    ],
  },
  {
    id: 'nba-players',
    name: 'NBA Players',
    items: [
      { id: 'nba-1', name: 'LeBron James' },
      { id: 'nba-2', name: 'Stephen Curry' },
      { id: 'nba-3', name: 'Kevin Durant' },
      { id: 'nba-4', name: 'Giannis Antetokounmpo' },
      { id: 'nba-5', name: 'Nikola Jokić' },
      { id: 'nba-6', name: 'Joel Embiid' },
      { id: 'nba-7', name: 'Luka Dončić' },
      { id: 'nba-8', name: 'Jayson Tatum' },
      { id: 'nba-9', name: 'Ja Morant' },
      { id: 'nba-10', name: 'Devin Booker' },
      { id: 'nba-11', name: 'Damian Lillard' },
      { id: 'nba-12', name: 'Anthony Davis' },
      { id: 'nba-13', name: 'Bam Adebayo' },
      { id: 'nba-14', name: 'Jimmy Butler' },
      { id: 'nba-15', name: 'Kawhi Leonard' },
      { id: 'nba-16', name: 'Paul George' },
      { id: 'nba-17', name: 'Karl-Anthony Towns' },
      { id: 'nba-18', name: 'Trae Young' },
      { id: 'nba-19', name: 'Donovan Mitchell' },
      { id: 'nba-20', name: 'Zion Williamson' },
      { id: 'nba-21', name: 'Michael Jordan' },
      { id: 'nba-22', name: 'Kobe Bryant' },
      { id: 'nba-23', name: 'Shaquille O\'Neal' },
      { id: 'nba-24', name: 'Tim Duncan' },
      { id: 'nba-25', name: 'Kevin Garnett' },
      { id: 'nba-26', name: 'Dirk Nowitzki' },
      { id: 'nba-27', name: 'Dwyane Wade' },
      { id: 'nba-28', name: 'Allen Iverson' },
      { id: 'nba-29', name: 'Larry Bird' },
      { id: 'nba-30', name: 'Magic Johnson' },
      { id: 'nba-31', name: 'Charles Barkley' },
      { id: 'nba-32', name: 'Scottie Pippen' },
      { id: 'nba-33', name: 'Dennis Rodman' },
      { id: 'nba-34', name: 'Reggie Miller' },
      { id: 'nba-35', name: 'Patrick Ewing' },
      { id: 'nba-36', name: 'John Stockton' },
      { id: 'nba-37', name: 'Karl Malone' },
      { id: 'nba-38', name: 'Clyde Drexler' },
      { id: 'nba-39', name: 'Hakeem Olajuwon' },
      { id: 'nba-40', name: 'David Robinson' },
      { id: 'nba-41', name: 'Chris Paul' },
      { id: 'nba-42', name: 'Russell Westbrook' },
      { id: 'nba-43', name: 'James Harden' },
      { id: 'nba-44', name: 'Carmelo Anthony' },
      { id: 'nba-45', name: 'Paul Pierce' },
      { id: 'nba-46', name: 'Ray Allen' },
      { id: 'nba-47', name: 'Tony Parker' },
      { id: 'nba-48', name: 'Manu Ginobili' },
      { id: 'nba-49', name: 'Vince Carter' },
      { id: 'nba-50', name: 'Tracy McGrady' },
    ],
  },
  {
    id: 'us-cities',
    name: 'US Cities',
    items: [
      { id: 'city-1', name: 'New York City' },
      { id: 'city-2', name: 'Los Angeles' },
      { id: 'city-3', name: 'Chicago' },
      { id: 'city-4', name: 'Houston' },
      { id: 'city-5', name: 'Phoenix' },
      { id: 'city-6', name: 'Philadelphia' },
      { id: 'city-7', name: 'San Antonio' },
      { id: 'city-8', name: 'San Diego' },
      { id: 'city-9', name: 'Dallas' },
      { id: 'city-10', name: 'San Jose' },
      { id: 'city-11', name: 'Austin' },
      { id: 'city-12', name: 'Jacksonville' },
      { id: 'city-13', name: 'Fort Worth' },
      { id: 'city-14', name: 'Columbus' },
      { id: 'city-15', name: 'Charlotte' },
      { id: 'city-16', name: 'Indianapolis' },
      { id: 'city-17', name: 'San Francisco' },
      { id: 'city-18', name: 'Seattle' },
      { id: 'city-19', name: 'Denver' },
      { id: 'city-20', name: 'Nashville' },
      { id: 'city-21', name: 'Oklahoma City' },
      { id: 'city-22', name: 'El Paso' },
      { id: 'city-23', name: 'Washington D.C.' },
      { id: 'city-24', name: 'Las Vegas' },
      { id: 'city-25', name: 'Louisville' },
      { id: 'city-26', name: 'Memphis' },
      { id: 'city-27', name: 'Portland' },
      { id: 'city-28', name: 'Baltimore' },
      { id: 'city-29', name: 'Milwaukee' },
      { id: 'city-30', name: 'Albuquerque' },
      { id: 'city-31', name: 'Tucson' },
      { id: 'city-32', name: 'Fresno' },
      { id: 'city-33', name: 'Sacramento' },
      { id: 'city-34', name: 'Mesa' },
      { id: 'city-35', name: 'Kansas City' },
      { id: 'city-36', name: 'Atlanta' },
      { id: 'city-37', name: 'Omaha' },
      { id: 'city-38', name: 'Colorado Springs' },
      { id: 'city-39', name: 'Raleigh' },
      { id: 'city-40', name: 'Long Beach' },
      { id: 'city-41', name: 'Virginia Beach' },
      { id: 'city-42', name: 'Minneapolis' },
      { id: 'city-43', name: 'Tampa' },
      { id: 'city-44', name: 'New Orleans' },
      { id: 'city-45', name: 'Arlington' },
      { id: 'city-46', name: 'Wichita' },
      { id: 'city-47', name: 'Bakersfield' },
      { id: 'city-48', name: 'Aurora' },
      { id: 'city-49', name: 'Anaheim' },
      { id: 'city-50', name: 'Santa Ana' },
      { id: 'city-51', name: 'Corpus Christi' },
      { id: 'city-52', name: 'Riverside' },
      { id: 'city-53', name: 'Lexington' },
      { id: 'city-54', name: 'St. Louis' },
      { id: 'city-55', name: 'Pittsburgh' },
      { id: 'city-56', name: 'Anchorage' },
      { id: 'city-57', name: 'Stockton' },
      { id: 'city-58', name: 'Cincinnati' },
      { id: 'city-59', name: 'St. Paul' },
      { id: 'city-60', name: 'Greensboro' },
    ],
  },
  {
    id: 'rock-bands',
    name: 'Rock Bands',
    items: [
      { id: 'rock-1', name: 'The Beatles' },
      { id: 'rock-2', name: 'Led Zeppelin' },
      { id: 'rock-3', name: 'The Rolling Stones' },
      { id: 'rock-4', name: 'Pink Floyd' },
      { id: 'rock-5', name: 'Queen' },
      { id: 'rock-6', name: 'AC/DC' },
      { id: 'rock-7', name: 'Nirvana' },
      { id: 'rock-8', name: 'Metallica' },
      { id: 'rock-9', name: 'U2' },
      { id: 'rock-10', name: 'Radiohead' },
      { id: 'rock-11', name: 'Foo Fighters' },
      { id: 'rock-12', name: 'Pearl Jam' },
      { id: 'rock-13', name: 'Soundgarden' },
      { id: 'rock-14', name: 'Alice in Chains' },
      { id: 'rock-15', name: 'Guns N\' Roses' },
      { id: 'rock-16', name: 'Aerosmith' },
      { id: 'rock-17', name: 'The Who' },
      { id: 'rock-18', name: 'Black Sabbath' },
      { id: 'rock-19', name: 'Deep Purple' },
      { id: 'rock-20', name: 'Fleetwood Mac' },
      { id: 'rock-21', name: 'Eagles' },
      { id: 'rock-22', name: 'Lynyrd Skynyrd' },
      { id: 'rock-23', name: 'The Doors' },
      { id: 'rock-24', name: 'Jimi Hendrix Experience' },
      { id: 'rock-25', name: 'Cream' },
      { id: 'rock-26', name: 'The Clash' },
      { id: 'rock-27', name: 'Ramones' },
      { id: 'rock-28', name: 'Sex Pistols' },
      { id: 'rock-29', name: 'The Smiths' },
      { id: 'rock-30', name: 'Joy Division' },
      { id: 'rock-31', name: 'R.E.M.' },
      { id: 'rock-32', name: 'Smashing Pumpkins' },
      { id: 'rock-33', name: 'Green Day' },
      { id: 'rock-34', name: 'Blink-182' },
      { id: 'rock-35', name: 'Weezer' },
      { id: 'rock-36', name: 'Rage Against the Machine' },
      { id: 'rock-37', name: 'System of a Down' },
      { id: 'rock-38', name: 'Tool' },
      { id: 'rock-39', name: 'Linkin Park' },
      { id: 'rock-40', name: 'Red Hot Chili Peppers' },
      { id: 'rock-41', name: 'Coldplay' },
      { id: 'rock-42', name: 'Muse' },
      { id: 'rock-43', name: 'Arctic Monkeys' },
      { id: 'rock-44', name: 'The Strokes' },
      { id: 'rock-45', name: 'Jack White / White Stripes' },
      { id: 'rock-46', name: 'Arcade Fire' },
      { id: 'rock-47', name: 'The National' },
      { id: 'rock-48', name: 'Wilco' },
      { id: 'rock-49', name: 'Phish' },
      { id: 'rock-50', name: 'Grateful Dead' },
    ],
  },
  {
    id: 'us-presidents',
    name: 'US Presidents',
    items: [
      { id: 'pres-1', name: 'George Washington' },
      { id: 'pres-2', name: 'John Adams' },
      { id: 'pres-3', name: 'Thomas Jefferson' },
      { id: 'pres-4', name: 'James Madison' },
      { id: 'pres-5', name: 'James Monroe' },
      { id: 'pres-6', name: 'John Quincy Adams' },
      { id: 'pres-7', name: 'Andrew Jackson' },
      { id: 'pres-8', name: 'Martin Van Buren' },
      { id: 'pres-9', name: 'William Henry Harrison' },
      { id: 'pres-10', name: 'John Tyler' },
      { id: 'pres-11', name: 'James K. Polk' },
      { id: 'pres-12', name: 'Zachary Taylor' },
      { id: 'pres-13', name: 'Millard Fillmore' },
      { id: 'pres-14', name: 'Franklin Pierce' },
      { id: 'pres-15', name: 'James Buchanan' },
      { id: 'pres-16', name: 'Abraham Lincoln' },
      { id: 'pres-17', name: 'Andrew Johnson' },
      { id: 'pres-18', name: 'Ulysses S. Grant' },
      { id: 'pres-19', name: 'Rutherford B. Hayes' },
      { id: 'pres-20', name: 'James A. Garfield' },
      { id: 'pres-21', name: 'Chester A. Arthur' },
      { id: 'pres-22', name: 'Grover Cleveland' },
      { id: 'pres-23', name: 'Benjamin Harrison' },
      { id: 'pres-24', name: 'William McKinley' },
      { id: 'pres-25', name: 'Theodore Roosevelt' },
      { id: 'pres-26', name: 'William Howard Taft' },
      { id: 'pres-27', name: 'Woodrow Wilson' },
      { id: 'pres-28', name: 'Warren G. Harding' },
      { id: 'pres-29', name: 'Calvin Coolidge' },
      { id: 'pres-30', name: 'Herbert Hoover' },
      { id: 'pres-31', name: 'Franklin D. Roosevelt' },
      { id: 'pres-32', name: 'Harry S. Truman' },
      { id: 'pres-33', name: 'Dwight D. Eisenhower' },
      { id: 'pres-34', name: 'John F. Kennedy' },
      { id: 'pres-35', name: 'Lyndon B. Johnson' },
      { id: 'pres-36', name: 'Richard Nixon' },
      { id: 'pres-37', name: 'Gerald Ford' },
      { id: 'pres-38', name: 'Jimmy Carter' },
      { id: 'pres-39', name: 'Ronald Reagan' },
      { id: 'pres-40', name: 'George H.W. Bush' },
      { id: 'pres-41', name: 'Bill Clinton' },
      { id: 'pres-42', name: 'George W. Bush' },
      { id: 'pres-43', name: 'Barack Obama' },
      { id: 'pres-44', name: 'Donald Trump' },
      { id: 'pres-45', name: 'Joe Biden' },
    ],
  },
  {
    id: 'bible-characters',
    name: 'Bible Characters',
    items: [
      { id: 'bib-1', name: 'Moses' },
      { id: 'bib-2', name: 'David' },
      { id: 'bib-3', name: 'Jesus' },
      { id: 'bib-4', name: 'Paul' },
      { id: 'bib-5', name: 'Abraham' },
      { id: 'bib-6', name: 'Noah' },
      { id: 'bib-7', name: 'Solomon' },
      { id: 'bib-8', name: 'Elijah' },
      { id: 'bib-9', name: 'Joshua' },
      { id: 'bib-10', name: 'Joseph' },
      { id: 'bib-11', name: 'Peter' },
      { id: 'bib-12', name: 'John' },
      { id: 'bib-13', name: 'James' },
      { id: 'bib-14', name: 'Matthew' },
      { id: 'bib-15', name: 'Luke' },
      { id: 'bib-16', name: 'Daniel' },
      { id: 'bib-17', name: 'Isaiah' },
      { id: 'bib-18', name: 'Jeremiah' },
      { id: 'bib-19', name: 'Samson' },
      { id: 'bib-20', name: 'Gideon' },
      { id: 'bib-21', name: 'Saul' },
      { id: 'bib-22', name: 'Jonathan' },
      { id: 'bib-23', name: 'Esther' },
      { id: 'bib-24', name: 'Ruth' },
      { id: 'bib-25', name: 'Mary' },
      { id: 'bib-26', name: 'Mary Magdalene' },
      { id: 'bib-27', name: 'Eve' },
      { id: 'bib-28', name: 'Sarah' },
      { id: 'bib-29', name: 'Rebekah' },
      { id: 'bib-30', name: 'Rachel' },
      { id: 'bib-31', name: 'Deborah' },
      { id: 'bib-32', name: 'Adam' },
      { id: 'bib-33', name: 'Cain' },
      { id: 'bib-34', name: 'Abel' },
      { id: 'bib-35', name: 'Job' },
      { id: 'bib-36', name: 'Jonah' },
      { id: 'bib-37', name: 'Ezekiel' },
      { id: 'bib-38', name: 'Nehemiah' },
      { id: 'bib-39', name: 'Ezra' },
      { id: 'bib-40', name: 'Goliath' },
      { id: 'bib-41', name: 'Caleb' },
      { id: 'bib-42', name: 'Aaron' },
      { id: 'bib-43', name: 'Judas Iscariot' },
      { id: 'bib-44', name: 'Thomas' },
      { id: 'bib-45', name: 'Andrew' },
      { id: 'bib-46', name: 'Philip' },
      { id: 'bib-47', name: 'Stephen' },
      { id: 'bib-48', name: 'Barnabas' },
      { id: 'bib-49', name: 'Timothy' },
      { id: 'bib-50', name: 'Silas' },
    ],
  },
  {
    id: 'movie-characters',
    name: 'Movie Characters',
    items: [
      { id: 'mov-1', name: 'Luke Skywalker' },
      { id: 'mov-2', name: 'Darth Vader' },
      { id: 'mov-3', name: 'Indiana Jones' },
      { id: 'mov-4', name: 'James Bond' },
      { id: 'mov-5', name: 'Tony Stark / Iron Man' },
      { id: 'mov-6', name: 'Batman' },
      { id: 'mov-7', name: 'Superman' },
      { id: 'mov-8', name: 'Spider-Man' },
      { id: 'mov-9', name: 'Hannibal Lecter' },
      { id: 'mov-10', name: 'The Joker' },
      { id: 'mov-11', name: 'Forrest Gump' },
      { id: 'mov-12', name: 'Jack Sparrow' },
      { id: 'mov-13', name: 'Ellen Ripley' },
      { id: 'mov-14', name: 'John McClane' },
      { id: 'mov-15', name: 'The Terminator' },
      { id: 'mov-16', name: 'Atticus Finch' },
      { id: 'mov-17', name: 'Vito Corleone' },
      { id: 'mov-18', name: 'Michael Corleone' },
      { id: 'mov-19', name: 'Travis Bickle' },
      { id: 'mov-20', name: 'Scarlett O\'Hara' },
      { id: 'mov-21', name: 'Clarice Starling' },
      { id: 'mov-22', name: 'Tyler Durden' },
      { id: 'mov-23', name: 'Neo' },
      { id: 'mov-24', name: 'Morpheus' },
      { id: 'mov-25', name: 'Gandalf' },
      { id: 'mov-26', name: 'Frodo Baggins' },
      { id: 'mov-27', name: 'Aragorn' },
      { id: 'mov-28', name: 'Harry Potter' },
      { id: 'mov-29', name: 'Hermione Granger' },
      { id: 'mov-30', name: 'Ron Weasley' },
      { id: 'mov-31', name: 'Captain America' },
      { id: 'mov-32', name: 'Thor' },
      { id: 'mov-33', name: 'Black Widow' },
      { id: 'mov-34', name: 'Thanos' },
      { id: 'mov-35', name: 'Wolverine' },
      { id: 'mov-36', name: 'Professor X' },
      { id: 'mov-37', name: 'Magneto' },
      { id: 'mov-38', name: 'Maximus' },
      { id: 'mov-39', name: 'Braveheart (William Wallace)' },
      { id: 'mov-40', name: 'Rocky Balboa' },
      { id: 'mov-41', name: 'John Wick' },
      { id: 'mov-42', name: 'Ethan Hunt' },
      { id: 'mov-43', name: 'Jason Bourne' },
      { id: 'mov-44', name: 'Katniss Everdeen' },
      { id: 'mov-45', name: 'Hermione Granger' },
      { id: 'mov-46', name: 'Rey' },
      { id: 'mov-47', name: 'Kylo Ren' },
      { id: 'mov-48', name: 'Yoda' },
      { id: 'mov-49', name: 'Obi-Wan Kenobi' },
      { id: 'mov-50', name: 'Gollum' },
    ],
  },
  {
    id: 'nfl-players',
    name: 'NFL Players',
    items: [
      { id: 'nfl-1', name: 'Tom Brady' },
      { id: 'nfl-2', name: 'Patrick Mahomes' },
      { id: 'nfl-3', name: 'Joe Montana' },
      { id: 'nfl-4', name: 'Jerry Rice' },
      { id: 'nfl-5', name: 'Lawrence Taylor' },
      { id: 'nfl-6', name: 'Emmitt Smith' },
      { id: 'nfl-7', name: 'Walter Payton' },
      { id: 'nfl-8', name: 'Barry Sanders' },
      { id: 'nfl-9', name: 'Peyton Manning' },
      { id: 'nfl-10', name: 'John Elway' },
      { id: 'nfl-11', name: 'Brett Favre' },
      { id: 'nfl-12', name: 'Dan Marino' },
      { id: 'nfl-13', name: 'Deion Sanders' },
      { id: 'nfl-14', name: 'Randy Moss' },
      { id: 'nfl-15', name: 'Terrell Owens' },
      { id: 'nfl-16', name: 'Bruce Smith' },
      { id: 'nfl-17', name: 'Reggie White' },
      { id: 'nfl-18', name: 'Ray Lewis' },
      { id: 'nfl-19', name: 'Junior Seau' },
      { id: 'nfl-20', name: 'Dick Butkus' },
      { id: 'nfl-21', name: 'Mike Ditka' },
      { id: 'nfl-22', name: 'Jim Brown' },
      { id: 'nfl-23', name: 'Marcus Allen' },
      { id: 'nfl-24', name: 'Tony Dorsett' },
      { id: 'nfl-25', name: 'Eric Dickerson' },
      { id: 'nfl-26', name: 'OJ Simpson' },
      { id: 'nfl-27', name: 'Ladainian Tomlinson' },
      { id: 'nfl-28', name: 'Adrian Peterson' },
      { id: 'nfl-29', name: 'Marshawn Lynch' },
      { id: 'nfl-30', name: 'Christian McCaffrey' },
      { id: 'nfl-31', name: 'Lamar Jackson' },
      { id: 'nfl-32', name: 'Josh Allen' },
      { id: 'nfl-33', name: 'Jalen Hurts' },
      { id: 'nfl-34', name: 'Justin Jefferson' },
      { id: 'nfl-35', name: 'Davante Adams' },
      { id: 'nfl-36', name: 'Stefon Diggs' },
      { id: 'nfl-37', name: 'Travis Kelce' },
      { id: 'nfl-38', name: 'Rob Gronkowski' },
      { id: 'nfl-39', name: 'Tony Gonzalez' },
      { id: 'nfl-40', name: 'Shannon Sharpe' },
      { id: 'nfl-41', name: 'Joe Burrow' },
      { id: 'nfl-42', name: 'Ja\'Marr Chase' },
      { id: 'nfl-43', name: 'Tua Tagovailoa' },
      { id: 'nfl-44', name: 'Aaron Rodgers' },
      { id: 'nfl-45', name: 'Russell Wilson' },
      { id: 'nfl-46', name: 'Dak Prescott' },
      { id: 'nfl-47', name: 'Nick Bosa' },
      { id: 'nfl-48', name: 'Myles Garrett' },
      { id: 'nfl-49', name: 'Micah Parsons' },
      { id: 'nfl-50', name: 'Sauce Gardner' },
    ],
  },
  {
    id: 'countries',
    name: 'Countries',
    items: [
      { id: 'cou-1', name: 'United States' },
      { id: 'cou-2', name: 'China' },
      { id: 'cou-3', name: 'Russia' },
      { id: 'cou-4', name: 'Germany' },
      { id: 'cou-5', name: 'United Kingdom' },
      { id: 'cou-6', name: 'France' },
      { id: 'cou-7', name: 'Japan' },
      { id: 'cou-8', name: 'Brazil' },
      { id: 'cou-9', name: 'India' },
      { id: 'cou-10', name: 'Canada' },
      { id: 'cou-11', name: 'Australia' },
      { id: 'cou-12', name: 'Italy' },
      { id: 'cou-13', name: 'Spain' },
      { id: 'cou-14', name: 'Mexico' },
      { id: 'cou-15', name: 'South Korea' },
      { id: 'cou-16', name: 'Argentina' },
      { id: 'cou-17', name: 'Saudi Arabia' },
      { id: 'cou-18', name: 'Turkey' },
      { id: 'cou-19', name: 'Netherlands' },
      { id: 'cou-20', name: 'Switzerland' },
      { id: 'cou-21', name: 'Sweden' },
      { id: 'cou-22', name: 'Norway' },
      { id: 'cou-23', name: 'Finland' },
      { id: 'cou-24', name: 'Denmark' },
      { id: 'cou-25', name: 'Poland' },
      { id: 'cou-26', name: 'Ukraine' },
      { id: 'cou-27', name: 'Egypt' },
      { id: 'cou-28', name: 'South Africa' },
      { id: 'cou-29', name: 'Nigeria' },
      { id: 'cou-30', name: 'Kenya' },
      { id: 'cou-31', name: 'Ethiopia' },
      { id: 'cou-32', name: 'Ghana' },
      { id: 'cou-33', name: 'Morocco' },
      { id: 'cou-34', name: 'Portugal' },
      { id: 'cou-35', name: 'Greece' },
      { id: 'cou-36', name: 'Israel' },
      { id: 'cou-37', name: 'Iran' },
      { id: 'cou-38', name: 'Pakistan' },
      { id: 'cou-39', name: 'Bangladesh' },
      { id: 'cou-40', name: 'Indonesia' },
      { id: 'cou-41', name: 'Thailand' },
      { id: 'cou-42', name: 'Vietnam' },
      { id: 'cou-43', name: 'Philippines' },
      { id: 'cou-44', name: 'New Zealand' },
      { id: 'cou-45', name: 'Cuba' },
      { id: 'cou-46', name: 'Colombia' },
      { id: 'cou-47', name: 'Peru' },
      { id: 'cou-48', name: 'Chile' },
      { id: 'cou-49', name: 'Venezuela' },
      { id: 'cou-50', name: 'Bolivia' },
    ],
  },
]

export const CATEGORIES: Category[] = [
  {
    id: 'none',
    name: 'None (Ordered List)',
    isNone: true,
    positions: [],
  },
  {
    id: 'football-team',
    name: 'Football Team',
    positions: [
      { id: 'qb', label: 'QB' },
      { id: 'rb', label: 'RB' },
      { id: 'wr1', label: 'WR1' },
      { id: 'wr2', label: 'WR2' },
      { id: 'te', label: 'TE' },
      { id: 'ol', label: 'OL' },
      { id: 'dl', label: 'DL' },
      { id: 'lb', label: 'LB' },
      { id: 'cb', label: 'CB' },
      { id: 's', label: 'S' },
      { id: 'k', label: 'K' },
      { id: 'c', label: 'Coach' },
    ],
  },
  {
    id: 'basketball-team',
    name: 'Basketball Team',
    positions: [
      { id: 'pg', label: 'PG' },
      { id: 'sg', label: 'SG' },
      { id: 'sf', label: 'SF' },
      { id: 'pf', label: 'PF' },
      { id: 'c', label: 'C' },
      { id: '6th', label: '6th Man' },
    ],
  },
  {
    id: 'baseball-team',
    name: 'Baseball Team',
    positions: [
      { id: 'catcher', label: 'C' },
      { id: '1b', label: '1B' },
      { id: '2b', label: '2B' },
      { id: '3b', label: '3B' },
      { id: 'ss', label: 'SS' },
      { id: 'lf', label: 'LF' },
      { id: 'cf', label: 'CF' },
      { id: 'rf', label: 'RF' },
      { id: 'sp', label: 'SP' },
      { id: 'rp', label: 'RP' },
      { id: 'dh', label: 'DH' },
    ],
  },
  {
    id: 'medieval-court',
    name: 'Medieval Court',
    positions: [
      { id: 'king', label: 'King' },
      { id: 'queen', label: 'Queen' },
      { id: 'knight', label: 'Knight' },
      { id: 'jester', label: 'Jester' },
      { id: 'wizard', label: 'Wizard' },
      { id: 'blacksmith', label: 'Blacksmith' },
      { id: 'archer', label: 'Archer' },
      { id: 'scout', label: 'Scout' },
    ],
  },
  {
    id: 'wild-west-town',
    name: 'Wild West Town',
    positions: [
      { id: 'sheriff', label: 'Sheriff' },
      { id: 'deputy', label: 'Deputy' },
      { id: 'outlaw', label: 'Outlaw' },
      { id: 'saloon-owner', label: 'Saloon Owner' },
      { id: 'doctor', label: 'Doctor' },
      { id: 'blacksmith-ww', label: 'Blacksmith' },
      { id: 'banker', label: 'Banker' },
      { id: 'cowboy', label: 'Cowboy' },
    ],
  },
  {
    id: 'pirate-ship',
    name: 'Pirate Ship',
    positions: [
      { id: 'captain', label: 'Captain' },
      { id: 'first-mate', label: 'First Mate' },
      { id: 'navigator', label: 'Navigator' },
      { id: 'cook', label: 'Cook' },
      { id: 'gunner', label: 'Gunner' },
      { id: 'lookout', label: 'Lookout' },
      { id: 'carpenter', label: 'Carpenter' },
      { id: 'musician', label: 'Musician' },
    ],
  },
  {
    id: 'superhero-team',
    name: 'Superhero Team',
    positions: [
      { id: 'leader', label: 'Leader' },
      { id: 'tank', label: 'Tank' },
      { id: 'speedster', label: 'Speedster' },
      { id: 'healer', label: 'Healer' },
      { id: 'tactician', label: 'Tactician' },
      { id: 'scout-sh', label: 'Scout' },
    ],
  },
  {
    id: 'heist-crew',
    name: 'Heist Crew',
    positions: [
      { id: 'mastermind', label: 'Mastermind' },
      { id: 'hacker', label: 'Hacker' },
      { id: 'muscle', label: 'Muscle' },
      { id: 'driver', label: 'Driver' },
      { id: 'safecracker', label: 'Safecracker' },
      { id: 'con-artist', label: 'Con Artist' },
      { id: 'lookout-h', label: 'Lookout' },
    ],
  },
  {
    id: 'space-crew',
    name: 'Space Crew',
    positions: [
      { id: 'commander', label: 'Commander' },
      { id: 'pilot', label: 'Pilot' },
      { id: 'engineer', label: 'Engineer' },
      { id: 'scientist', label: 'Scientist' },
      { id: 'medic', label: 'Medic' },
      { id: 'communications', label: 'Communications' },
      { id: 'weapons', label: 'Weapons Officer' },
    ],
  },
]
